2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Current SDK version is 0.15.1
2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Configure stats pid to 271901
2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Loading settings from /home/mib07150/.config/wandb/settings
2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Loading settings from /home/mib07150/git/sapient/KataBasicFlax/wandb/settings
2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_init.py:_log_setup():507] Logging user logs to /home/mib07150/git/sapient/KataBasicFlax/wandb/run-20231230_075914-4cw7go9l/logs/debug.log
2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_init.py:_log_setup():508] Logging internal logs to /home/mib07150/git/sapient/KataBasicFlax/wandb/run-20231230_075914-4cw7go9l/logs/debug-internal.log
2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f5fb0221690>
2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_init.py:init():547] calling init triggers
2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_init.py:init():596] starting backend
2023-12-30 07:59:14,499 INFO    MainThread:271901 [wandb_init.py:init():600] setting up manager
2023-12-30 07:59:14,503 INFO    MainThread:271901 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-12-30 07:59:14,505 INFO    MainThread:271901 [wandb_init.py:init():606] backend started and connected
2023-12-30 07:59:14,509 INFO    MainThread:271901 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-12-30 07:59:14,509 INFO    MainThread:271901 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-12-30 07:59:14,510 INFO    MainThread:271901 [wandb_init.py:init():700] updated telemetry
2023-12-30 07:59:14,512 INFO    MainThread:271901 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-12-30 07:59:14,524 ERROR   MainThread:271901 [wandb_init.py:init():763] encountered error: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-12-30 07:59:14,620 ERROR   MainThread:271901 [wandb_init.py:init():1168] The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
Traceback (most recent call last):
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1150, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 769, in init
    raise error
wandb.errors.AuthenticationError: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-12-30 07:59:29,138 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Current SDK version is 0.15.1
2023-12-30 07:59:29,138 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Configure stats pid to 271901
2023-12-30 07:59:29,138 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Loading settings from /home/mib07150/.config/wandb/settings
2023-12-30 07:59:29,138 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Loading settings from /home/mib07150/git/sapient/KataBasicFlax/wandb/settings
2023-12-30 07:59:29,138 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-30 07:59:29,138 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-30 07:59:29,138 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-30 07:59:29,138 INFO    MainThread:271901 [wandb_init.py:_log_setup():507] Logging user logs to /home/mib07150/git/sapient/KataBasicFlax/wandb/run-20231230_075929-7iaqfk85/logs/debug.log
2023-12-30 07:59:29,138 INFO    MainThread:271901 [wandb_init.py:_log_setup():508] Logging internal logs to /home/mib07150/git/sapient/KataBasicFlax/wandb/run-20231230_075929-7iaqfk85/logs/debug-internal.log
2023-12-30 07:59:29,138 INFO    MainThread:271901 [wandb_init.py:init():547] calling init triggers
2023-12-30 07:59:29,138 INFO    MainThread:271901 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-12-30 07:59:29,138 INFO    MainThread:271901 [wandb_init.py:init():596] starting backend
2023-12-30 07:59:29,138 INFO    MainThread:271901 [wandb_init.py:init():600] setting up manager
2023-12-30 07:59:29,142 INFO    MainThread:271901 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-12-30 07:59:29,143 INFO    MainThread:271901 [wandb_init.py:init():606] backend started and connected
2023-12-30 07:59:29,146 INFO    MainThread:271901 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-12-30 07:59:29,146 INFO    MainThread:271901 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-12-30 07:59:29,146 INFO    MainThread:271901 [wandb_init.py:init():700] updated telemetry
2023-12-30 07:59:29,147 INFO    MainThread:271901 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-12-30 07:59:41,966 WARNING MainThread:271901 [wandb_init.py:init():1172] interrupted
Traceback (most recent call last):
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1150, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 740, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2023-12-30 07:59:43,456 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Current SDK version is 0.15.1
2023-12-30 07:59:43,456 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Configure stats pid to 271901
2023-12-30 07:59:43,456 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Loading settings from /home/mib07150/.config/wandb/settings
2023-12-30 07:59:43,456 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Loading settings from /home/mib07150/git/sapient/KataBasicFlax/wandb/settings
2023-12-30 07:59:43,456 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-30 07:59:43,456 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-30 07:59:43,456 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-30 07:59:43,456 INFO    MainThread:271901 [wandb_init.py:_log_setup():507] Logging user logs to /home/mib07150/git/sapient/KataBasicFlax/wandb/run-20231230_075943-a9sasfz2/logs/debug.log
2023-12-30 07:59:43,456 INFO    MainThread:271901 [wandb_init.py:_log_setup():508] Logging internal logs to /home/mib07150/git/sapient/KataBasicFlax/wandb/run-20231230_075943-a9sasfz2/logs/debug-internal.log
2023-12-30 07:59:43,456 INFO    MainThread:271901 [wandb_init.py:init():547] calling init triggers
2023-12-30 07:59:43,456 INFO    MainThread:271901 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-12-30 07:59:43,456 INFO    MainThread:271901 [wandb_init.py:init():596] starting backend
2023-12-30 07:59:43,456 INFO    MainThread:271901 [wandb_init.py:init():600] setting up manager
2023-12-30 07:59:43,461 INFO    MainThread:271901 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-12-30 07:59:43,463 INFO    MainThread:271901 [wandb_init.py:init():606] backend started and connected
2023-12-30 07:59:43,466 INFO    MainThread:271901 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-12-30 07:59:43,466 INFO    MainThread:271901 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-12-30 07:59:43,466 INFO    MainThread:271901 [wandb_init.py:init():700] updated telemetry
2023-12-30 07:59:43,467 INFO    MainThread:271901 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-12-30 08:00:14,084 WARNING MainThread:271901 [wandb_init.py:init():1172] interrupted
Traceback (most recent call last):
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1150, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 740, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2023-12-30 08:00:55,341 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Current SDK version is 0.15.1
2023-12-30 08:00:55,341 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Configure stats pid to 271901
2023-12-30 08:00:55,341 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Loading settings from /home/mib07150/.config/wandb/settings
2023-12-30 08:00:55,341 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Loading settings from /home/mib07150/git/sapient/KataBasicFlax/wandb/settings
2023-12-30 08:00:55,341 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-30 08:00:55,341 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-30 08:00:55,341 INFO    MainThread:271901 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-30 08:00:55,342 INFO    MainThread:271901 [wandb_init.py:_log_setup():507] Logging user logs to /home/mib07150/git/sapient/KataBasicFlax/wandb/run-20231230_080055-gedhs1l7/logs/debug.log
2023-12-30 08:00:55,342 INFO    MainThread:271901 [wandb_init.py:_log_setup():508] Logging internal logs to /home/mib07150/git/sapient/KataBasicFlax/wandb/run-20231230_080055-gedhs1l7/logs/debug-internal.log
2023-12-30 08:00:55,342 INFO    MainThread:271901 [wandb_init.py:init():547] calling init triggers
2023-12-30 08:00:55,342 INFO    MainThread:271901 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-12-30 08:00:55,342 INFO    MainThread:271901 [wandb_init.py:init():596] starting backend
2023-12-30 08:00:55,342 INFO    MainThread:271901 [wandb_init.py:init():600] setting up manager
2023-12-30 08:00:55,346 INFO    MainThread:271901 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-12-30 08:00:55,347 INFO    MainThread:271901 [wandb_init.py:init():606] backend started and connected
2023-12-30 08:00:55,350 INFO    MainThread:271901 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-12-30 08:00:55,350 INFO    MainThread:271901 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-12-30 08:00:55,350 INFO    MainThread:271901 [wandb_init.py:init():700] updated telemetry
2023-12-30 08:00:55,351 INFO    MainThread:271901 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-12-30 08:01:09,023 WARNING MainThread:271901 [wandb_init.py:init():1172] interrupted
Traceback (most recent call last):
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1150, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 740, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mib07150/prog/miniconda3/envs/py311/lib/python3.11/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
